name: vertical_listtile
description: Vertical listtile for you. You can add any 3 widgets you want inside the colum on the container.
version: 0.0.5
homepage: https://github.com/Haticenurcoskunn/
repository: https://github.com/Haticenurcoskunn/Vertical-Listtile
documentation: https://github.com/Haticenurcoskunn/Vertical-Listtile

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:

 